analytics/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

app_name = 'analytics'

urlpatterns = [
    path('product/<slug>/new_feedback',
         login_required(views.FeedbackNew.as_view()),
         name='feedback_new'),
]

clients/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

app_name = 'clients'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path(
        'accounts/profile/',
        login_required(views.ProfileView.as_view()),
        name='base_profile'
    ),
    path(
        'accounts/profile/<int:pk>/edit/',
        login_required(views.EditProfileView.as_view()),
        name='edit_profile'
    ),
]

core/urls.py
from django.urls import path

from .views import (
    ItemDetailView,
    CheckoutView,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    CatalogView,
    AboutView
)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('catalog/', CatalogView.as_view(), name='catalog'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
]

templates/about.html
{% extends 'base.html' %}
{% block head_title %}О нас{% endblock %}
{% block content %}
    <div class="container pt-3">
        <h2>О компании</h2>
        <p>
            Интернет-магазин основан в 1999 году!!! Работаем с часами с 1994
            года!
            Самые большие розничные салоны по представленному в них
            ассортименту.
        </p>
        <p> Контактный телефон: +7 (555) 555-55-55</p>

        <h2>Адреса самовывоза</h2>
        <ul class="list-group mb-3 z-depth-1">
            {% for address in addresses %}
                <li class="list-group-item d-flex justify-content-between lh-condensed">
                    <div>{{ address }}</div>
                </li>
            {% empty %}
                <p>Пока нет доступных адресов :(</p>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
    <link rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
    <style type="text/css">
        html,
        body,
        header,
        .carousel {
            height: 60vh;
        }

        @media (max-width: 740px) {

            html,
            body,
            header,
            .carousel {
                height: 100vh;
            }
        }

        @media (min-width: 800px) and (max-width: 850px) {

            html,
            body,
            header,
            .carousel {
                height: 100vh;

            }
        }


    </style>
</head>

{% include "navbar.html" %}

<body>

<div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show"
                 role="alert" id="message_container">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert"
                        aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endif %}
</div>

{% block content %}
{% endblock content %}

{% block extra_body %}
{% endblock %}

{% include "scripts.html" %}

{% block extra_scripts %}
{% endblock extra_scripts %}
</body>
</html>

templates/catalog.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %} Каталог {% endblock %}
{% block extra_head %}
    <style>
        /* The sidebar menu */
        .sidebar {
            height: 100%; /* 100% Full-height */
            width: 0; /* 0 width - change this with JavaScript */
            position: fixed; /* Stay in place */
            z-index: 1; /* Stay on top */
            top: 0;
            left: 20px;
            overflow-x: hidden; /* Disable horizontal scroll */
            padding-top: 70px; /* Place content 60px from the top */
            transition: 0.5s; /* 0.5 second transition effect to slide in the sidebar */
        }

        /* Position and style the close button (top right corner) */
        .sidebar .closebtn {
            position: absolute;
            top: 60px;
            right: 20px;
            font-size: 36px;
            margin-left: 50px;
        }

        /* The button used to open the sidebar */
        .openbtn {
            font-size: 15px;
            cursor: pointer;
            background-color: #111;
            color: white;
            padding: 10px 15px;
            border: none;
        }

        .openbtn:hover {
            background-color: #444;
        }

        /* Style page content - use this if you want to push the page content to the right when you open the side navigation */
        #main {
            transition: margin-left .5s; /* If you want a transition effect */
            padding: 0 0 40px 100px;
        }

    </style>
{% endblock %}

{% block content %}
    <div id="mySidebar" class="sidebar">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        <span class="navbar-brand">Фильтры:</span>
        <form action="" method="get">
            <div class="row wow fadeIn">
                <button class="btn btn-sm btn-primary" type="submit">
                    Применить
                </button>
                <a class="btn btn-sm btn-default"
                   href="{% url 'core:catalog' %}">Сбросить</a>
            </div>
            {{ filter.form|crispy }}
            <div class="row wow fadeIn">
                <button class="btn btn-sm btn-primary" type="submit">
                    Применить
                </button>
                <a class="btn btn-sm btn-default"
                   href="{% url 'core:catalog' %}">Сбросить</a>
            </div>
        </form>
    </div>
    <div id="main">
        <button class="openbtn" onclick="openNav()">&#9776; Фильтры
        </button>
        <section class="text-center mt-4 mb-4">

            <div class="row wow fadeIn">

                {% for item in filter.qs %}
                    <div class="col-lg-3 col-md-6 mb-4">

                        <div class="card">

                            <div class="overlay text-center">
                                <a href="{{ item.get_absolute_url }}">
                                    <img src="{{ item.image.url }}"
                                         class="card-img-top"
                                         style="height: 20rem; width: auto;">
                                </a>
                            </div>

                            <div class="card-body text-center">
                                <h5>
                                    <strong>
                                        <a href="{{ item.get_absolute_url }}"
                                           class="dark-grey-text">{{ item.title }}</a>
                                    </strong>
                                </h5>

                                <h4 class="font-weight-bold blue-text">
                                    <strong> {{ item.price.price }}
                                        ₽ </strong>
                                </h4>

                            </div>

                        </div>

                    </div>
                {% empty %}
                    <p> По вашему запросу ничего не найдено :( Попробуйте
                        изменить параметры поиска</p>
                {% endfor %}
            </div>

        </section>
        <!--Section: Products v.3-->

        <!--Pagination-->

        {% if is_paginated %}
            <nav class="d-flex justify-content-center wow fadeIn">
                <ul class="pagination pg-blue">

                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link"
                               href="?page={{ page_obj.previous_page_number }}"
                               aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                                <span class="sr-only">Previous</span>
                            </a>
                        </li>
                    {% endif %}

                    <li class="page-item active">
                        <a class="page-link"
                           href="?page={{ page_obj.number }}">{{ page_obj.number }}
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>

                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link"
                               href="?page={{ page_obj.next_page_number }}"
                               aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                                <span class="sr-only">Next</span>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}

    </div>
{% endblock content %}

{% block extra_scripts %}
    <script>
        function openNav() {
            document.getElementById("mySidebar").style.width = "300px";
            document.getElementById("main").style.marginLeft = "300px";
        }

        function closeNav() {
            document.getElementById("mySidebar").style.width = "0";
            document.getElementById("main").style.marginLeft = "0";
        }
    </script>
{% endblock %}

templates/checkout.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}Подтвердить заказ{% endblock %}

{% block content %}
  <main >
    <div class="container wow fadeIn">
      <h2 class="my-5 h2 text-center">Подтверждение заказа</h2>
      <div class="row">
        <div class="col-md-8 mb-4">
          <div class="card">
            <form method="POST" class="card-body">
              {% csrf_token %}
{#                {{ form }}#}


                <h3>Выберите адрес самовывоза</h3>

                <div class="d-block my-3">
                {% for choice in form.fields.pickup_address.queryset %}
                    <div class="custom-control custom-radio">
                      <input id="{{ choice.address }}" name="pickup_address" value="{{ choice.pk }}" type="radio" class="custom-control-input" required>
                      <label class="custom-control-label" for="{{ choice.address }}">{{ choice.address }}</label>
                    </div>
                {% endfor %}
              </div>

              <h3>Выберите способ оплаты</h3>

              <div class="d-block my-3">
                {% for value, name in form.fields.payment_option.choices %}
                <div class="custom-control custom-radio">
                  <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio" class="custom-control-input" required>
                  <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
                </div>
                {% endfor %}
              </div>

              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Подтвердить заказ</button>

            </form>

          </div>

        </div>

        <div class="col-md-4 mb-4">
          {% include "order_snippet.html" %}
        </div>

      </div>

    </div>
  </main>

{% endblock content %}

templates/footer.html
<footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.facebook.com/mdbootstrap" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/MDBootstrap" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="https://dribbble.com/mdbootstrap" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="https://pinterest.com/mdbootstrap" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="http://codepen.io/mdbootstrap/" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
    </div>
    <!--/.Copyright-->

  </footer>

templates/home.html
{% extends "base.html" %}

{% block head_title %}Watch-commerce{% endblock %}

{% block content %}

    <div id="myCarousel" class="carousel slide carousel-fade"
         data-ride="carousel">
    <div class="carousel-inner">
        {% for object in object_list %}
            <div class="carousel-item {% if forloop.first %} active{% endif %}">
                <div class="mask flex-center">
                    <div class="container">
                        <div class="row align-items-center">
                            <div class="col-md-5 col-12 order-1 text-center">
                                <img src="{{ object.image.url }}"
                                     class="mx-auto" alt="slide">
                            </div>
                            <div class="col-md-7 col-12 order-2">
                                <h4>{{ object.title }}</h4>
                                <p>{{ object.description }}</p>
                                <a href="{{ object.get_absolute_url }}"
                                   class="btn btn-dark btn-md my-2">
                                    Подробнее
                                </a>
                                <a href="{{ object.get_add_to_cart_url }}"
                                   class="btn btn-primary btn-md my-0">
                                    Добавить в корзину
                                    <i class="fas fa-shopping-cart ml-1"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        <a class="carousel-control-prev" href="#myCarousel" role="button"
           data-slide="prev"> <span class="carousel-control-prev-icon"
                                    aria-hidden="true"></span> <span
                class="sr-only">Previous</span> </a> <a
            class="carousel-control-next" href="#myCarousel" role="button"
            data-slide="next"> <span class="carousel-control-next-icon"
                                     aria-hidden="true"></span> <span
            class="sr-only">Next</span> </a>
    </div>
    <!--slide end-->
    <div class="row d-flex justify-content-center wow fadeIn ">
        <div class="container">
            {% include 'analytics/feedbacks.html' %}
        </div>
    </div>
{% endblock %}

{% block extra_scripts %}
    <script nonce="">
        $('#myCarousel').carousel({
            interval: 6000,
        })
    </script>
{% endblock %}

templates/navbar.html
{% load cart_template_tags %}

<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

        <!-- Brand -->
        <a class="navbar-brand waves-effect" href="/">
            <strong class="blue-text">Watch-commerce</strong>
        </a>

        <!-- Collapse -->
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Links -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <!-- Left -->
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link waves-effect"
                       href="{% url 'core:catalog' %}">Каталог
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link waves-effect"
                       href="{% url 'core:about' %}">О нас
                    </a>
                </li>
            </ul>

            <!-- Right -->
            <ul class="navbar-nav nav-flex-icons">
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link waves-effect"
                           href="{% url 'clients:base_profile' %}">
                            <span class="clearfix d-none d-sm-inline-block"> Личный кабинет ({{ request.user }})</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'core:order-summary' %}"
                           class="nav-link waves-effect">
                            <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
                            <i class="fas fa-shopping-cart"></i>
                            <span class="clearfix d-none d-sm-inline-block"> Корзина </span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link waves-effect"
                           href="{% url 'logout' %}">
                            <span class="clearfix d-none d-sm-inline-block"> Выход </span>
                        </a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link waves-effect"
                           href="{% url 'login' %}">
                            <span class="clearfix d-none d-sm-inline-block"> Войти </span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link waves-effect"
                           href="{% url 'clients:register' %}">
                            <span class="clearfix d-none d-sm-inline-block"> Зарегистрироваться </span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>

    </div>
</nav>

templates/order_snippet.html
<div class="col-md-12 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Ваша корзина</span>
    <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
    </h4>
    <ul class="list-group mb-3 z-depth-1">
    {% for order_item in order.items.all %}
    <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
        <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title}}</h6>
        </div>
        <span class="text-muted">{{ order_item.get_final_price }} ₽</span>
    </li>
    {% endfor %}
    <li class="list-group-item d-flex justify-content-between">
        <span>Итого</span>
        <strong>{{ order.get_total_price }} ₽</strong>
    </li>
    </ul>
</div>

templates/order_summary.html
{% extends "base.html" %}
{% block head_title %}Корзина{% endblock %}
{% block content %}
    <main>
        <div class="container mt-3">

            <div class="table-responsive text-nowrap">
                <h2>Заказ</h2>
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Название модели</th>
                        <th scope="col">Цена</th>
                        <th scope="col">Количество</th>
                        <th scope="col">Итого</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for order_item in object.items.all %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ order_item.item.title }}</td>
                            <td>{{ order_item.item.price.price }} ₽</td>
                            <td>
                                <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i
                                        class="fas fa-minus mr-2"></i></a>
                                {{ order_item.quantity }}
                                <a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i
                                        class="fas fa-plus ml-2"></i></a>
                            </td>
                            <td> {{ order_item.get_final_price }} ₽
                                <a style='color: red;'
                                   href="{% url 'core:remove-from-cart' order_item.item.slug %}">
                                    <i class="fas fa-trash float-right"></i>
                                </a>
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan='5'>Ваша корзина пуста</td>
                        </tr>
                        <tr>
                            <td colspan="5">
                                <a class='btn btn-primary float-right'
                                   href='{% url "core:catalog" %}'>Вернуться в
                                    магазин</a>
                            </td>
                        </tr>
                    {% endfor %}
                    {% if object.get_total_price %}
                        <tr>
                            <td colspan="4"><b>Итого</b></td>
                            <td><b>{{ object.get_total_price }} ₽</b></td>
                        </tr>
                        <tr>
                            <td colspan="5">
                                <a class='btn btn-warning float-right ml-2'
                                   href='{% url "core:checkout" %}'>Подтвердить
                                    заказ</a>
                                <a class='btn btn-primary float-right'
                                   href='{% url "core:catalog" %}'>Вернуться в
                                    магазин</a>
                            </td>
                        </tr>
                    {% endif %}
                    </tbody>
                </table>

            </div>

        </div>
    </main>

{% endblock content %}

templates/product.html
{% extends "base.html" %}

{% block head_title %}Детали продукта{% endblock %}

{% block content %}

    <div class="container dark-grey-text mt-5">

        <!--Grid row-->
        <div class="row wow fadeIn">

            <!--Grid column-->
            <div class="col-md-6 mb-4 overlay text-center">
                <img src="{{ object.image.url }}" class="img-fluid" alt="">
            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-md-6 mb-4">

                <!--Content-->
                <div class="p-5">

                    <h3> {{ object.brand.name }} </h3>

                    <p class="lead font-weight-bold">{{ object.title }}</p>
                    <p class="lead">
                        <strong> {{ object.price.price }} ₽ </strong>
                    </p>

                    <a href="{{ object.get_add_to_cart_url }}"
                       class="btn btn-primary btn-md my-0 p">
                        Добавить в корзину
                        <i class="fas fa-shopping-cart ml-1"></i>
                    </a>
                    {% if client_has_ordered_model %}
                        <a href="{% url 'analytics:feedback_new' slug=object.slug %}"
                           class="btn btn-green btn-md my-0 p">
                            Оставить отзыв
                        </a>
                    {% endif %}
                </div>
                <!--Content-->

            </div>
            <!--Grid column-->

        </div>
        <!--Grid row-->
        <div class="row d-flex justify-content-center wow fadeIn">

            <!--Grid column-->
            <div class="col-md-6 text-center">
                <h4 class="my-4 h4">Описание</h4>
                <p>{{ object.description }}</p>
            </div>
            <!--Grid column-->
            <div class="col-md-6 text-center">
                                <h4 class="my-4 h4">Характеристики</h4>
                <table class="table text-center">
                    <tbody>
                    <tr>
                        <th scope="row">Тип механизма</th>
                        <td>{{ object.mechanism }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Стекло</th>
                        <td>{{ object.glass }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Цвет браслета</th>
                        <td>{{ object.band.color }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Материал браслета</th>
                        <td>{{ object.band.material }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Цвет корпуса</th>
                        <td>{{ object.case.color }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Материал корпуса</th>
                        <td>{{ object.case.material }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Страна производитель
                        </th>
                        <td>{{ object.brand.country }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Гарантия</th>
                        <td>{{ object.brand.warranty }} Год
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <!--Grid row-->
        <div class="row d-flex justify-content-center wow fadeIn ">
            <div class="container">
                {% include 'analytics/feedbacks.html' %}
            </div>
        </div>
    </div>

{% endblock content %}

templates/scripts.html
{% load static %}
  
<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
  // Animations initialization
  new WOW().init();
</script>

<script>
    var message_ele = document.getElementById("message_container");
    setTimeout(function(){
       message_ele.style.display = 'None';
    }, 3000);
</script>