clients/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

app_name = 'clients'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path(
        'accounts/profile/',
        login_required(views.ProfileView.as_view()),
        name='base_profile'
    ),
    path(
        'accounts/profile/<int:pk>/edit/',
        login_required(views.EditProfileView.as_view()),
        name='edit_profile'
    ),
]

core/urls.py
from django.urls import path

from .views import (
    ItemDetailView,
    CheckoutView,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    CatalogView,
    AboutView
)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('catalog/', CatalogView.as_view(), name='catalog'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
]

clients/models.py
from django.contrib.auth.models import User
from django.db import models

from clients.validators import PhoneRegexValidator


class Client(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='client',
        verbose_name='Клиент',
        null=True
    )
    firstname = models.CharField(
        max_length=255,
        verbose_name='Имя',
        null=True
    )
    lastname = models.CharField(
        max_length=255,
        verbose_name='Фамилия',
        null=True
    )
    phone = models.CharField(
        max_length=255,
        verbose_name='Телефон',
        validators=[PhoneRegexValidator()],
    )
    email = models.EmailField(
        max_length=255,
        verbose_name='Email для связи',
        null=True
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Время создания',
    )

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'

    def __str__(self):
        return f"{self.firstname} {self.lastname}"

core/models/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import reverse

from core.models.auxilary_models import (
    WatchBrand,
    Watchband,
    GlassMaterial,
    WatchCase,
    WatchMechanism
)
from core.utils import create_ref_code


class Watch(models.Model):
    class Meta:
        verbose_name = "Модель часов"
        verbose_name_plural = "Модели часов"

    title = models.CharField(
        verbose_name="Название модели",
        max_length=100
    )
    description = models.TextField(
        verbose_name="Описание от производителя"
    )
    image = models.ImageField()
    slug = models.SlugField()
    brand = models.ForeignKey(
        WatchBrand,
        on_delete=models.CASCADE,
        verbose_name='Название бренда',
        related_name='watch'
    )
    band = models.ForeignKey(
        Watchband,
        on_delete=models.CASCADE,
        verbose_name='Ремешок',
        related_name='watch'
    )
    glass = models.ForeignKey(
        GlassMaterial,
        on_delete=models.CASCADE,
        verbose_name='Стекло',
        related_name='watch'
    )
    case = models.ForeignKey(
        WatchCase,
        on_delete=models.CASCADE,
        verbose_name='Корпус',
        related_name='watch'
    )
    mechanism = models.ForeignKey(
        WatchMechanism,
        on_delete=models.CASCADE,
        verbose_name='Механизм',
        related_name='watch'
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })


class Price(models.Model):
    class Meta:
        verbose_name = "Цена на модель"
        verbose_name_plural = "Цены на модели"

    watch = models.OneToOneField(
        Watch,
        on_delete=models.CASCADE,
        verbose_name="Модель часов",
        related_name='price'
    )
    price = models.FloatField(
        verbose_name="Цена часов в рублях"
    )

    def __str__(self):
        return f"Цена на {self.watch}: {self.price}"


class OrderItem(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="order_item",
        verbose_name="Клиент"
    )
    ordered = models.BooleanField(
        default=False,
        verbose_name="Заказано"
    )
    item = models.ForeignKey(
        Watch,
        on_delete=models.CASCADE,
        verbose_name="Товар"
    )
    quantity = models.IntegerField(
        verbose_name="Количество",
        default=1
    )

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_final_price(self):
        return self.quantity * self.item.price.price


class PickupAddress(models.Model):
    class Meta:
        verbose_name = "Адрес самовывоза"
        verbose_name_plural = "Адреса самовывоза"

    address = models.TextField(
        verbose_name="Полный адрес"
    )
    phone = models.CharField(
        max_length=20,
        verbose_name="Контактный телефон"
    )

    def __str__(self):
        return self.address


class Order(models.Model):
    CASH_CHOICE = 'cash'
    CARD_CHOICE = 'card'

    PAYMENT_CHOICES = (
        (CASH_CHOICE, 'Наличными'),
        (CARD_CHOICE, 'Картой')
    )

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='order',
        verbose_name="Клиент"
    )
    ref_code = models.CharField(
        verbose_name="Код товара",
        default=create_ref_code,
        max_length=20
    )
    items = models.ManyToManyField(OrderItem)
    created_at = models.DateTimeField(
        verbose_name="Создан",
        auto_now_add=True
    )
    ordered_date = models.DateTimeField(
        verbose_name="Дата заказа",
        null=True
    )
    ordered = models.BooleanField(
        verbose_name="Заказано",
        default=False
    )
    payment = models.CharField(
        verbose_name="Способ оплаты",
        max_length=50,
        choices=PAYMENT_CHOICES,
        default=PAYMENT_CHOICES[0][0]
    )
    pickup_address = models.ForeignKey(
        PickupAddress,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name="С какого адреса заберут заказ"
    )
    is_bought_out = models.BooleanField(
        verbose_name="Выкуплен",
        default=False
    )

    def __str__(self):
        return f"Заказ №{self.ref_code}. Клиент: {self.user.client}"

    def get_total_price(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total

clients/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django import forms
from django.forms import ModelForm

from .models import Client
from .validators import PhoneRegexValidator


class RegistrationForm(UserCreationForm):
    phone = forms.CharField(label="Контактный телефон",
                            validators=[PhoneRegexValidator()])

    class Meta:
        model = User
        fields = ('username', 'phone')

    def save(self, **kwargs):
        user = super().save()

        Client.objects.create(
            user=user,
            phone=self.cleaned_data["phone"],
        )
        return user


class EditProfileForm(ModelForm):
    phone = forms.CharField(label="Контактный телефон")
    email = forms.CharField(label="E-mail для связи", required=False)
    firstname = forms.CharField(label="Имя", required=False)
    lastname = forms.CharField(label="Фамилия", required=False)

    class Meta:
        model = Client
        fields = ('firstname', 'lastname', 'email', 'phone')

clients/views.py
from django.views import generic
from django.db.models import Q

from clients.forms import RegistrationForm, EditProfileForm
from clients.models import Client
from django.shortcuts import redirect


class RegisterView(generic.FormView):
    template_name = 'registration/signup.html'
    form_class = RegistrationForm
    success_url = '/accounts/login'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class EditProfileView(generic.UpdateView):
    model = Client
    form_class = EditProfileForm
    template_name = 'clients/edit_profile.html'
    success_url = '/accounts/profile'


class ProfileView(generic.TemplateView):
    template_name = 'clients/profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user

        try:
            client = Client.objects.get(user=user)
        except Client.DoesNotExist:
            if any((user.is_superuser, user.is_staff)):
                client = Client.objects.create(
                    user=user,
                    firstname="Admin",
                    lastname=user.username,
                    phone="+71111111111",
                )
            else:
                return None

        current_orders = user.order.filter(
            Q(ordered=True) &
            Q(is_bought_out=False)
        )
        past_orders = user.order.filter(
            Q(ordered=True) &
            Q(is_bought_out=True)
        )

        context['client'] = client
        context['current_orders'] = current_orders
        context['past_orders'] = past_orders

        return context

    def render_to_response(self, context, **response_kwargs):
        if context is None:
            return redirect('error')
        return super().render_to_response(context, **response_kwargs)

templates/clients/edit_profile.html
{% extends "registration/base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %}Редактировать данные{% endblock %}

{% block content %}
  <main>
    <div class="container">
      <section class="mt-4 ">
        <div class="row wow fadeIn">
          <div class='col-6 offset-3'>
            <h1>Редактировать данные</h1>
            <form class="edit-profile" id="editprofile_form" method="post">
              {% csrf_token %}
              {{ form|crispy }}
              <button class='btn btn-primary' type="submit"> Сохранить изменения</button>
            </form>
          </div>
        </div>
      </section>
    </div>
  </main>
{% endblock %}

templates/clients/profile.html
{% extends 'base.html' %}

{% block head_title %}Личный кабинет{% endblock %}

{% block content %}
    <div class="container mt-3">
        <h2>Личный кабинет</h2>
        <div class="pt-3">
            <ul class="nav nav-tabs" id="myTab" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="current-orders-tab"
                       data-toggle="tab" href="#current-orders" role="tab"
                       aria-controls="current-orders" aria-selected="true">Активные
                        заказы</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="past-orders-tab" data-toggle="tab"
                       href="#past-orders" role="tab"
                       aria-controls="past-orders"
                       aria-selected="false">Завершенные заказы</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="info-tab" data-toggle="tab"
                       href="#info" role="tab" aria-controls="info"
                       aria-selected="false">Личная информация</a>
                </li>
            </ul>
            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="current-orders"
                     role="tabpanel" aria-labelledby="current-orders-tab">
                    <div class="container">

                        <div class="table-responsive text-nowrap">

                            <table class="table">
                                <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Номер заказа</th>
                                    <th scope="col">Цена</th>
                                    <th scope="col">Способ оплаты</th>
                                    <th scope="col">Адрес самовывоза</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for order in current_orders %}
                                    <tr>
                                        <th scope="row">{{ forloop.counter }}</th>
                                        <td>{{ order.ref_code }}</td>
                                        <td>{{ order.get_total_price }} ₽</td>
                                        <td>{{ order.get_payment_display }}</td>
                                        <td>{{ order.pickup_address }}</td>
                                    </tr>
                                {% empty %}
                                    <tr>
                                        <td colspan='5'>Нет активных закзов
                                        </td>
                                    </tr>
                                    <tr>
                                        <td colspan="5">
                                            <a class='btn btn-primary float-right'
                                               href='{% url "core:catalog" %}'>Вернуться
                                                в магазин</a>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="tab-pane fade" id="past-orders" role="tabpanel"
                     aria-labelledby="past-orders-tab">
                    <div class="container">

                        <div class="table-responsive text-nowrap">

                            <table class="table">
                                <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Номер заказа</th>
                                    <th scope="col">Цена</th>
                                    <th scope="col">Способ оплаты</th>
                                    <th scope="col">Адрес самовывоза</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for order in past_orders %}
                                    <tr>
                                        <th scope="row">{{ forloop.counter }}</th>
                                        <td>{{ order.ref_code }}</td>
                                        <td>{{ order.get_total_price }} ₽</td>
                                        <td>{{ order.get_payment_display }}</td>
                                        <td>{{ order.pickup_address }}</td>
                                    </tr>
                                {% empty %}
                                    <tr>
                                        <td colspan='5'>У вас еще нет прошедших
                                            заказов
                                        </td>
                                    </tr>
                                    <tr>
                                        <td colspan="5">
                                            <a class='btn btn-primary float-right'
                                               href='{% url "core:catalog" %}'>Вернуться
                                                в магазин</a>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>

                </div>
                <div class="tab-pane fade" id="info" role="tabpanel"
                     aria-labelledby="info-tab">
                    <!--Grid row-->
                    <div class="row d-flex justify-content-center wow fadeIn ">
                        <div class="col-md-8">
                            <br>
                            <h3> Текущие данные: </h3>
                            <br>
                            <div class="tab-pane fade show active" id="home"
                                 role="tabpanel" aria-labelledby="home-tab">
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>ФИО</label>
                                    </div>
                                    <div class="col-md-6">
                                        <p>{{ client.firstname }} {{ client.lastname }}</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>E-mail</label>
                                    </div>
                                    <div class="col-md-6">
                                        <p>{{ client.email }}</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Телефон для связи</label>
                                    </div>
                                    <div class="col-md-6">
                                        <p>{{ client.phone }}</p>
                                    </div>
                                </div>
                                <a class='btn btn-primary'
                                   href='{% url 'clients:edit_profile' pk=client.id %}'>редактировать</a>
                            </div>
                        </div>
                    </div>
                    <!--Grid row-->
                </div>
            </div>
        </div>

    </div>
{% endblock %}